theme: minima
title: Designconstant
description: civilization mechanology
-


source: dir
destination: dir
safe: build
file.fnmatch
exclude: ["readme.md", "***readme.md] 
jekyll new: .saasc-cache/
jekyll new: .jekyll-cache/
jekyll new: gemfiles
jekyll new: gemfile.lock
jekyll new: node_modules
jekyll new: vendor/bundle/
jekyll new: vendor/cache/
jekyll new: vendor/gems/
jekyll new: vendor/ruby/
jekyll new: .htaccess
include: [DIR,FILES...]
keep_files: [DIR,FILE,...]
timezone: TIMEZONE
encoding: ENCODING
---
layout: _posts
title: :Anthology jurisprudence
---
layout: _layout
null
none
none
default _config
_config.yml
defaults:
-
scope:
path:_about
values:
layout: "default"
values
scope 
type
scope
defaults:
-
scope:
path:
types:
values:
posts.
pages,posts,drafts,type
path,values/pair
defaults:
-
scope:
path: ""
type: "pages"
values:
layout: "mysite"
-
scope:
path:
type:
values:

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "my-site"
  -
    scope:
      path: "projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      author: "Mr. Hall"

    archive: # optional, default is true

    [![.github/workflows/_config.yml](https://github.com/Occipital-Creation/Jurisprudence-NewCity-/actions/workflows/_config.yml/badge.svg?event=check_suite)](https://github.com/Occipital-Creation/Jurisprudence-NewCity-/actions/workflows/_config.yml)
          
